workspace(name = "bazel-example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "6b65cb7917b4d1709f9410ffe00ecf3e160edf674b78c54a894471320862184f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.39.0/rules_go-v0.39.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.39.0/rules_go-v0.39.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.20.2")


##############
# Aspect GCC toolchain

http_archive(
	name = "aspect_gcc_toolchain",
	strip_prefix = "gcc-toolchain-0.4.2",
	type = "tar.gz",
	urls = [
		"https://github.com/aspect-build/gcc-toolchain/archive/refs/tags/0.4.2.tar.gz",
	],
)

load("@aspect_gcc_toolchain//toolchain:repositories.bzl", "gcc_toolchain_dependencies")

gcc_toolchain_dependencies()

load("@aspect_gcc_toolchain//toolchain:defs.bzl", "ARCHS", "gcc_register_toolchain")

gcc_register_toolchain(
	name = "gcc_toolchain_aarch64",
	target_arch = ARCHS.aarch64,
)

gcc_register_toolchain(
	name = "gcc_toolchain_x86",
	target_arch = ARCHS.x86_64,
)
