workspace(name = "bazel-example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_cc",
    sha256 = "3d9e271e2876ba42e114c9b9bc51454e379cbf0ec9ef9d40e2ae4cec61a31b40",
    strip_prefix = "rules_cc-0.0.6",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.6/rules_cc-0.0.6.tar.gz"],
)


##############
# Aspect GCC toolchain

http_archive(
	name = "aspect_gcc_toolchain",
	strip_prefix = "gcc-toolchain-0.4.2",
	type = "tar.gz",
	urls = [
		"https://github.com/aspect-build/gcc-toolchain/archive/refs/tags/0.4.2.tar.gz",
	],
)

load("@aspect_gcc_toolchain//toolchain:repositories.bzl", "gcc_toolchain_dependencies")

gcc_toolchain_dependencies()

load("@aspect_gcc_toolchain//toolchain:defs.bzl", "ARCHS", "gcc_register_toolchain")

gcc_register_toolchain(
	name = "gcc_toolchain_aarch64",
	target_arch = ARCHS.aarch64,
)

gcc_register_toolchain(
	name = "gcc_toolchain_x86",
	target_arch = ARCHS.x86_64,
)
